trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'd9ea37f2-471f-483a-afc7-5176fc965b72'

  # Web app name
  webAppName: 'webcompress'

  # Environment name
  environmentName: 'webcompress'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  displayName: Build and Deploy
  pool:
    vmImage: $(vmImageName)

  steps:
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/FE'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: drop

  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy: webcompress'
    inputs:
      azureSubscription: $(azureSubscription)
      appType: webAppLinux
      WebAppName: $(webAppName)
      packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
      RuntimeStack: 'NODE|10.10'
      StartupCommand: 'npm run start'
      ScriptType: 'Inline Script'
      InlineScript: |
        npm install
        npm run build --if-present